freebsd_task:
        install_script: ASSUME_ALWAYS_YES=yes pkg bootstrap -f ; pkg install -y kyua pkgconf python3 bzip2
        script:
                - mkdir build && cd build
                - ../configure $EXTRA_ARGS
                - make -j4 || make V=1
        check_script:
                - cd build
                - make check || { kyua report --verbose ; exit 1 ; }
        matrix:
                - name: freebsd14-amd64
                  freebsd_instance:
                     image_family: freebsd-14-0-snap
                  env:
                     #EXTRA_ARGS: --with-asan --with-ubsan
                     # There are still a few occurrences of this error (adding offset to NULL pointer)
                     CPPFLAGS: -fno-sanitize=pointer-overflow -ftrivial-auto-var-init=pattern
